GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "new new title",
  "author": "new newauthor",
  "url": "new new url",
  "likes": "115"
}